### ISSUE TITLE
[Bug] V10: request for and contested roll raise the errors

### ISSUE THREAD

**Issue by paranoicsan** [ironmonk88/monks-tokenbar#272]
First of all thanks for developing such amazing module!

FVTT v10.284
Module 1.0.70 (it's the only active module in the system)

Request Role dialog is not rendered:
```javascript
TypeError: An error occurred while rendering SavingThrowApp 50. key.split is not a function or its return value is not iterable
    at Object.getProperty (commons.js:1698:24)
    at Localization.localize (foundry.js:6689:27)
    at Object.localize (foundry.js:6985:52)
    at Object.c (handlebars.min.js:27:19853)
    at eval (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:15:149)
    at h (handlebars.min.js:27:17870)
    at c (handlebars.min.js:27:6899)
    at handlebars.min.js:27:7554
    at Array.forEach (<anonymous>)
    at handlebars.min.js:27:7522
```

The same for contested role:
```javascript
Uncaught TypeError: key.split is not a function or its return value is not iterable
    at Object.getProperty (commons.js:1698:24)
    at Localization.localize (foundry.js:6689:27)
    at i18n (monks-tokenbar.js:32:22)
    at contestedroll.js:27:32
    at Array.find (<anonymous>)
    at contestedroll.js:26:61
    at Array.map (<anonymous>)
    at new ContestedRollApp (contestedroll.js:21:37)
    at TokenBar.click (base-rolls.js:117:46)
    at HTMLDivElement.i (jquery.min.js:2:88918)
```

**Comment by paranoicsan** [comment]
Seems to be fixed with 6e37632d3eaa8fa743bb1effecab14fc5b2dc170 in [1.0.71](https://github.com/ironmonk88/monks-tokenbar/commit/6e37632d3eaa8fa743bb1effecab14fc5b2dc170)

Nice work! 💪🏻
