### ISSUE TITLE
[BUG] Request Tool Check Macro Error (5e)

### ISSUE THREAD

**Issue by harrisog** [ironmonk88/monks-tokenbar#291]
**Describe the bug**
Saving a tokenbar roll request for a tool check in DnD5e as a macro through the UI and test-running it returns the following error:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'id')
[Detected 3 packages: monks-tokenbar, advanced-macros, lib-wrapper]
    at MonksTokenBar.findBestRequest (monks-tokenbar.js:635:47)
    at new SavingThrowApp (savingthrow.js:36:38)
    at MonksTokenBarAPI.requestRoll (monks-tokenbar-api.js:44:27)
    at eval (eval at <anonymous> (Macros.js:59:16), <anonymous>:4:25)
    at Macro.eval (eval at <anonymous> (Macros.js:59:16), <anonymous>:5:7)
    at :gift:Macro.prototype._executeScript#advanced-macros (Macros.js:61:16)
    at :gift:call_wrapper [as call_wrapper] (libWrapper-wrapper.js:591:14)
    at :gift:Macro.prototype._executeScript#0 (libWrapper-wrapper.js:189:20)
    at Macro.renderMacro [as renderContent] (Macros.js:210:16)
    at Macro.executeMacro (Macros.js:231:23)
    at :gift:call_wrapper [as call_wrapper] (libWrapper-wrapper.js:591:14)
    at :gift:Macro.prototype.execute#0 (libWrapper-wrapper.js:189:20)
    at MacroConfig._onExecute (foundry.js:65072:17)
```
Sending the request for a tool check through the UI works normally. Test-running other types of checks as macros also works normally.

**To Reproduce**
1. Give tool item to actor and select
2. Use tokenbar UI to generate tool check request for selected actor
3. Execute autogenerated macro  

**Expected behavior**
Should send a roll request to chat

**Please complete as much of the following information as possible:**
 - Browser : Chrome
 - Foundry Version : 10.288
 - System : 5e
 - Module version: latest
 - Are there any errors in the console [e.g. press F12 and look for red text] : see above
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction : yes, only enabled modules are libwrapper, socketlib, advanced-macros, module management+ and Monk's tokenbar

**Comment by ironmonk88** [comment]
Changes should be in the latest release.
