### ISSUE TITLE
[BUG] Convert to Lootable is not converting items correctly

### ISSUE THREAD

**Issue by Brimcon** [ironmonk88/monks-tokenbar#329]
**Describe the bug**
When converting an NPC to a lootable the item5e.type is blank for all items converted this way.

**To Reproduce**
1. Create a NPC Actor on the canvas (Acolyte from Monster SRD is fastest)
2. Create Player Actor (Importing Akra, Dragonborn Cleric is fastest)
3. Convert Acolyte to Lootable via button in Actor Controls. Having Monk's Enhanced Journal enabled will expedite this process
4. Attempt to drag the converted item into the Player Actor's inventory.
5. Observe error in Console log.

**Expected behavior**
The item in question enters the Inventory and is converted without an error.

**Screenshots**
Will add some if requested.

**Please complete as much of the following information as possible:**
 - Browser: Chrome
 - Foundry Version 10.291
 - System D&D5e
 - Module version: 10.5
 - Are there any errors in the console? Console log below
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. Only modules enabled are TokenBar and Enhanced Journal.

**Additional context**
```commons.js:4098 Uncaught (in promise) Error: Item5e [NE3H9kVPNpCFlxFu] Model Validation Errors
[Item5e.type]: may not be a blank string
    at SchemaField._validateType (commons.js:4098:15)
    at SchemaField.validate (commons.js:3824:37)
    at Item5e.validate (commons.js:5492:35)
    at new DataModel (commons.js:5269:26)
    at new Document (commons.js:5811:3)
    at new BaseItem (commons.js:8590:3)
    at new ClientDocumentMixin (foundry.js:13053:5)
    at new Item (foundry.js:19553:1)
    at new Item5e (item.mjs:9:16)
    at Item5e.fromDropData (foundry.js:13737:33)```

While may be out of the scope of this error report, I have found similar issues when trying to convert to Item Piles. An actor is created, but not as an Item Pile and is completely empty. The actor that is created is an NPC. Not sure if intentional or not.

**Comment by HonkLord** [comment]
Standard Loot Sheet does work when items are added manually.  The conversion of actor items to loot sheet items is failing.

Loot sheet will also not allow opening/viewing any items details when converted from actors but works fine in loot sheet when added manually from actors.

**Comment by ironmonk88** [comment]
Should be fixed in the latest version
