### ISSUE TITLE
[BUG] Brief description of your issue

### ISSUE THREAD

**Issue by dmizrahi** [ironmonk88/monks-tokenbar#401]
Hello !

**Describe the bug**
There is a bug in request contested roll from a macro.
Exemple macro on a blank new world with only monks token bar activated
`game.MonksTokenBar.requestContestedRoll({token:game.canvas.tokens.children[0].children[1], request:[{"type":"skill","key":"ath","slug":"skill:ath"}]},{token:game.canvas.tokens.children[0].children[0], request:[{"type":"skill","key":"ath","slug":"skill:ath"}]},{silent:true, fastForward:false, rollMode:'roll', callback: async (results) => {
    console.log(results);
}});`

**To Reproduce**
1. New scene
2. put 2 token on it
3. set up the macro
4. execute macro

**Expected behavior**
The macro should execute the contested roll

**Please complete as much of the following information as possible:**
 - Browser foundry server
 - Foundry Version : V11
 - System : D&D5e
 - Module version : 11.02
 - Error : 
 - `Uncaught (in promise) TypeError: Cannot read properties of null (reading 'type')
    at MonksTokenBar.getRequestName (monks-tokenbar.js:804:25)
    at contestedroll.js:77:44
    at Array.map (<anonymous>)
    at contestedroll.js:76:37
    at Array.map (<anonymous>)
    at ContestedRollApp.requestRoll (contestedroll.js:71:43)
    at MonksTokenBarAPI.requestContestedRoll (monks-tokenbar-api.js:68:43)
    at Macro.eval (eval at #executeScript (foundry.js:22792:16), <anonymous>:3:21)
    at #executeScript (foundry.js:22796:17)
    at Macro.execute (foundry.js:22744:35)`
 - No other module installed

Thank you for this amazing work

**Comment by ironmonk88** [comment]
Fixed in the latest version
