### ISSUE TITLE
Request Roll and Contested Roll not working

### ISSUE THREAD

**Issue by nuck1234** [ironmonk88/monks-tokenbar#468]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Select Request a Roll' and complete the fields as required.
<img width="805" alt="Screenshot 2024-03-04 at 14 30 37" src="https://github.com/ironmonk88/monks-tokenbar/assets/59491370/4e03ba3a-db16-4362-a471-686b96295328">

2. Click on 'Request with Roll'
3. See error
<img width="1447" alt="Screenshot 2024-03-04 at 14 31 03" src="https://github.com/ironmonk88/monks-tokenbar/assets/59491370/2c3710f4-2daa-4422-b7f9-d4de04877bd1">

<img width="296" alt="Screenshot 2024-03-04 at 14 31 17" src="https://github.com/ironmonk88/monks-tokenbar/assets/59491370/f5b5d41e-3c37-4102-aa2b-67ae4e12d6de">

4. The same thing occurs in Contested Roll.

**Expected behavior**
The roll should happen

**Please complete as much of the following information as possible:**
 - Browser: Foundry itself
 - Foundry Version 11.315 Stable
 - System dnd5e 3.0.3
 - Module version 11.22

Are there any errors in the console? See attached log from console.

<img width="549" alt="Screenshot 2024-03-04 at 14 32 41" src="https://github.com/ironmonk88/monks-tokenbar/assets/59491370/15d71ae0-5652-4417-aff8-353d8aad5bb6">

Have you tried using Find the Culprit to make sure it isn't a module interaction? Yes.

**Additional context**

**Comment by benjamin-ping-xu** [comment]
I'm having the same issue. To add on some information, there are 4 interactions I've tested:

| Button         | Mode              | Working? |
|----------------|-------------------|----------|
| Request Roll   | Request           | Yes      |
|                | Request with Roll | No       |
| Contested Roll | Request           | No       |
|                | Request with Roll | No       |

For Request Roll (Request with Roll), the error message is as provided by nuck1234.

For Contested Roll (Request, Request with Roll), the error message is different. See below.

Contested Roll (Request)
```
chat-message.mjs:251 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'formula')
    at ChatMessage5e._enrichRollTooltip (chat-message.mjs:251:54)
    at chat-message.mjs:233:51
    at NodeList.forEach (<anonymous>)
    at ChatMessage5e._enrichChatCard (chat-message.mjs:232:46)
    at ChatMessage5e.getHTML (chat-message.mjs:58:10)
    at async ChatLog.postOne (foundry.js:85744:18)
```

Contested Roll (Request with Roll)
```
chat-message.mjs:251 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'formula')
    at ChatMessage5e._enrichRollTooltip (chat-message.mjs:251:54)
    at chat-message.mjs:233:51
    at NodeList.forEach (<anonymous>)
    at ChatMessage5e._enrichChatCard (chat-message.mjs:232:46)
    at ChatMessage5e.getHTML (chat-message.mjs:58:10)
    at async ChatLog.postOne (foundry.js:85744:18)
    at async ChatLog.updateMessage (foundry.js:85808:7)
```

**Comment by nuck1234** [comment]
Thank you for pointing it out. I was not sure if it was or not. I think bejamin provided the rest of the detail I missed.
