### ISSUE TITLE
[BUG] Requested rolls not displaying results

### ISSUE THREAD

**Issue by EvldoaTV** [ironmonk88/monks-tokenbar#476]
Since the latest update 23/03/2024 of the 5e system in foundry
requested rolls are not completing and displaying the result

this is the error given

chat-message.mjs:271 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading '_formula')
[Detected 1 package: system:dnd5e]
    at ChatMessage5e._enrichRollTooltip (chat-message.mjs:271:54)
    at chat-message.mjs:254:51
    at NodeList.forEach (<anonymous>)
    at ChatMessage5e._enrichChatCard (chat-message.mjs:253:46)
    at ChatMessage5e.getHTML (chat-message.mjs:73:10)
    at async ChatLog.updateMessage (foundry.js:85793:20)
_
using chrome
foundry ver 11 build 315
dnd 5e ver 3.1.0

**Comment by YegoRomka** [comment]
+++
I have such error!
Can i force this issue here like on stackowerflow?

**Comment by EvldoaTV** [comment]
essentially what Im seeing in the chat card   pops up, the player cam click to roll and then the dice rolls but no result is shown
this has only started happening after the most recent update to the 5e system

**Comment by EvldoaTV** [comment]
replicated with only monks token bar mod active

chat-message.mjs:271 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_formula')
    at ChatMessage5e._enrichRollTooltip (chat-message.mjs:271:54)
    at chat-message.mjs:254:51
    at NodeList.forEach (<anonymous>)
    at ChatMessage5e._enrichChatCard (chat-message.mjs:253:46)
    at ChatMessage5e.getHTML (chat-message.mjs:73:10)
    at async ChatLog.updateMessage (foundry.js:85793:20)
_

**Comment by quincey78** [comment]
Same issue noted here:
Foundry v.11 Build 315
D&D5e 3.1.1
Monk's Tokenbar v 11.15

I'm really hoping for this to be fixed soon

**Comment by ironmonk88** [comment]
If Dnd5e would stop messing around with things, and fix their errors this might actually stay fixed.
