### ISSUE TITLE
[BUG] D&D5e Token bar doesn't appear on launch.

### ISSUE THREAD

**Issue by wardrumsjr** [ironmonk88/monks-tokenbar#533]
**Describe the bug**
Token bar doesn't appear on launch, have to swap scenes to appear. It is is not interactable, and has no movement options.

**To Reproduce**
Launch a D&D5e world.

**Expected behavior**
Tokenbar will not appear.

**Please complete as much of the following information as possible:**
 - FoundryVTT Program
 - Foundry Version 12 Build 331
 - System: D&D5e (Tested and worked in PF2e
 - 12.03
 - Error: Error thrown in hooked function 'ready' for hook 'ready'. "dnd5e.levelingMode" is not a registered game setting
[Detected 3 packages: force-client-settings(2.5.0), lib-wrapper(1.12.15.0), monks-tokenbar(12.03)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁Hooks.onError#lib-wrapper (listeners.js:140:11)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:187:52)
    at #call (foundry.js:636:36)
    at Hooks.callAll (foundry.js:589:17)
    at Game.setupGame (foundry.js:9098:11)
    at async Game._initializeGameView (foundry.js:10432:5)
    at async Game.initialize (foundry.js:8995:5)
 - Did not use find the culprit, but tested on a world with no other modules active.

**Comment by ironmonk88** [comment]
Update to the latest D&D.

**Comment by CaosFR** [comment]
So the last update in only for DnD 4.X ? It's extremely important information if that's the case.

**Comment by Ghostwalker83** [comment]
I received the same issue when using PF2e version 6.7.2, oddly enough only on one of my three games:
This is the console error message:

[Detected 1 package: monks-tokenbar(12.04)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at #call (foundry.js:636:36)
    at Hooks.callAll (foundry.js:589:17)
    at Game.setupGame (foundry.js:9098:11)
    at async Game._initializeGameView (foundry.js:10432:5)
    at async Game.initialize (foundry.js:8995:5)Caused by: ReferenceError: tinyMCE is not defined
[Detected 1 package: monks-tokenbar(12.04)]
    at Object.ready [as fn] (monks-tokenbar.js:435:9)
    at #call (foundry.js:632:20)
    at Hooks.callAll (foundry.js:589:17)
    at Game.setupGame (foundry.js:9098:11)
    at async Game._initializeGameView (foundry.js:10432:5)
    at async Game.initialize (foundry.js:8995:5)

Downgrading to TokenBar 12.02 and returning to 12.04 does resolve the issue, though.
